### ISSUE TITLE
Make use of "--device(s)" for XGBoost

### ISSUE THREAD

**Issue by Alexsandruss** [IntelPython/scikit-learn_bench#102]
CPU and GPU configs for XGBoost have only few differences: in `data-format` (pandas vs cudf) and `tree-method` (hist vs gpu_hist). Dispatching for them with `--devices(s)` argument will simplify configs.

**Comment by lulin789** [comment]
SKL_Bench_Team1 working on this issue

**Comment by Alexsandruss** [comment]
Device support for XGBoost is integrated in refactoring(https://github.com/IntelPython/scikit-learn_bench/pull/133), so this issue will become solved in future
