### ISSUE TITLE
svm.py fails with IndexError

### ISSUE THREAD

**Issue by mericas** [IntelPython/scikit-learn_bench#113]
Following instructions in https://medium.com/intel-analytics-software/leverage-intel-optimizations-in-scikit-learn-f562cb9d5544 get errors in all cases.  Typical error message is

INFO: python sklearn_bench/svm.py --arch mericas --data-format pandas --data-order F --dtype float64 --max-cache-size 2 --probability -C 1.0 --kernel rbf --device none --file-X-train data/klaverjas_x_train.npy --file-y-train data/klaverjas_y_train.npy --file-X-test data/klaverjas_x_test.npy --file-y-test data/klaverjas_y_test.npy --dataset-name klaverjas

WARNING: Error in benchmark:

Traceback (most recent call last):
  File "/home/mericas/scikit-learn_bench-master/sklearn_bench/svm.py", line 107, in <module>
    bench.run_with_context(params, main)
  File "/home/mericas/scikit-learn_bench-master/bench.py", line 572, in run_with_context
    function()
  File "/home/mericas/scikit-learn_bench-master/sklearn_bench/svm.py", line 63, in main
    train_acc = bench.accuracy_score(y_train, y_pred)
  File "/home/mericas/scikit-learn_bench-master/bench.py", line 347, in accuracy_score
    return columnwise_score(y_true, y_pred, lambda y1, y2: np.mean(y1 == y2))
  File "/home/mericas/scikit-learn_bench-master/bench.py", line 342, in columnwise_score
    return [score_func(y[i], yp[i]) for i in range(y.shape[1])]
IndexError: tuple index out of rangeCASE sklearn,svm  --data-format pandas --data-order F --dtype float64 --max-cache-size 2 --probability  -C 1.0 --kernel rbf --device none JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

Also notice that svm fails using scikit-learn_bench/blob/master/configs/blogs/skl_2021_3.json

**Comment by mericas** [comment]
Am I the only one seeing this?

**Comment by dmitrii-kriukov** [comment]
Hello, @mericas, thanks for creating an issue.
We have reproduced the problem and fixed it by #116

**Comment by mericas** [comment]
Thank you, it does work now.
