### ISSUE TITLE
lot of memory allocations becomes bottleneck

### ISSUE THREAD

**Issue by jkr0103** [IntelPython/scikit-learn_bench#120]
I captured perf data for most of the algorithms and see there are lot many memory allocations happens during the run which become bottleneck. Please refer attached screenshot.

Is there a way to fine tune the memory allocations? like any env variable or cmmandline arguments?

![perf data for nusvc](https://user-images.githubusercontent.com/15154645/200760427-2be55442-1990-426f-aa2f-8b285fa7292c.png)

**Comment by Alexsandruss** [comment]
Memory allocations are expected especially during generation of synthetic datasets.
I can't add anything else without knowledge of what are you exactly running on this screenshot.
There is no variable or argument to control it.

**Comment by jkr0103** [comment]
Is it possible to split the "generation of synthetic datasets" and "actual benchmark execution" between two processes. My case is I am trying to run these benchmarking algorithms in SGX where we have memory constraints. Hence would like to know if synthetic datasets can be generated separately so that we do only benchmarks execution inside SGX.

**Comment by jkr0103** [comment]
sorry closed it by mistake

**Comment by napetrov** [comment]
Would be addressed with pre-fetch capability in this PR -https://github.com/IntelPython/scikit-learn_bench/pull/133
