### ISSUE TITLE
Facing issues while running benchmark on Ubuntu 18.04

### ISSUE THREAD

**Issue by vasanth-intel** [IntelPython/scikit-learn_bench#123]
Hi,

I am facing below issue while executing `ridge` algorithm on Ubuntu 18.04. Looks like I may not be using the right versions of dependent packages like pandas, numpy, scipy, scikit-learn, scikit-learn-intelex, etc.. I had installed the scikit-learn and the dependent packages using command `pip3 install -r sklearn_bench/requirements.txt`. I have listed the versions installed in my system after the error logs. Would like to know if we have any specific package version requirements for Ubuntu 18.04. Thanks!

===============================================================

~/scikit-learn_bench$ python3 runner.py --configs configs/sklearn/performance/ridge.json --output-file results/ridge.json
INFO: Datasets folder is not set, using local folder
INFO: Config: configs/sklearn/performance/ridge.json
INFO: ridge algorithm: 2 case(s), 2 dataset(s)

INFO: python sklearn_bench/ridge.py --arch intel-WilsonCity --data-format pandas --data-order F --dtype float32 --device none --alpha 5 --file-X-train data/synthetic-regression-X-train-10000000x20.npy --file-y-train data/synthetic-regression-y-train-10000000x20.npy --file-X-test data/synthetic-regression-X-train-10000000x20.npy --file-y-test data/synthetic-regression-y-train-10000000x20.npy --dataset-name synthetic_regression

WARNING: Error in benchmark:
Traceback (most recent call last):
  File "sklearn_bench/ridge.py", line 19, in <module>
    import bench
  File "/home/intel/scikit-learn_bench/bench.py", line 38
    raise ValueError(f'Impossible to get data type of {type(data)}')
                                                                  ^
SyntaxError: invalid syntaxCASE sklearn,ridge  --data-format pandas --data-order F --dtype float32 --device none --alpha 5 JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

INFO: python sklearn_bench/ridge.py --arch intel-WilsonCity --data-format pandas --data-order F --dtype float64 --device none --alpha 5 --file-X-train data/synthetic-regression-X-train-10000000x20.npy --file-y-train data/synthetic-regression-y-train-10000000x20.npy --file-X-test data/synthetic-regression-X-train-10000000x20.npy --file-y-test data/synthetic-regression-y-train-10000000x20.npy --dataset-name synthetic_regression

WARNING: Error in benchmark:
Traceback (most recent call last):
  File "sklearn_bench/ridge.py", line 19, in <module>
    import bench
  File "/home/intel/scikit-learn_bench/bench.py", line 38
    raise ValueError(f'Impossible to get data type of {type(data)}')
                                                                  ^
SyntaxError: invalid syntaxCASE sklearn,ridge  --data-format pandas --data-order F --dtype float64 --device none --alpha 5 JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

INFO: python sklearn_bench/ridge.py --arch intel-WilsonCity --data-format pandas --data-order F --dtype float32 --device none --alpha 5 --file-X-train data/synthetic-regression-X-train-2000000x100.npy --file-y-train data/synthetic-regression-y-train-2000000x100.npy --file-X-test data/synthetic-regression-X-train-2000000x100.npy --file-y-test data/synthetic-regression-y-train-2000000x100.npy --dataset-name synthetic_regression

WARNING: Error in benchmark:
Traceback (most recent call last):
  File "sklearn_bench/ridge.py", line 19, in <module>
    import bench
  File "/home/intel/scikit-learn_bench/bench.py", line 38
    raise ValueError(f'Impossible to get data type of {type(data)}')
                                                                  ^
SyntaxError: invalid syntaxCASE sklearn,ridge  --data-format pandas --data-order F --dtype float32 --device none --alpha 5 JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

INFO: python sklearn_bench/ridge.py --arch intel-WilsonCity --data-format pandas --data-order F --dtype float64 --device none --alpha 5 --file-X-train data/synthetic-regression-X-train-2000000x100.npy --file-y-train data/synthetic-regression-y-train-2000000x100.npy --file-X-test data/synthetic-regression-X-train-2000000x100.npy --file-y-test data/synthetic-regression-y-train-2000000x100.npy --dataset-name synthetic_regression

WARNING: Error in benchmark:
Traceback (most recent call last):
  File "sklearn_bench/ridge.py", line 19, in <module>
    import bench
  File "/home/intel/scikit-learn_bench/bench.py", line 38
    raise ValueError(f'Impossible to get data type of {type(data)}')
                                                                  ^
SyntaxError: invalid syntaxCASE sklearn,ridge  --data-format pandas --data-order F --dtype float64 --device none --alpha 5 JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

WARNING: benchmark running had runtime errors
~/scikit-learn_bench$

===============================================================

~/scikit-learn_bench$ pip3 list
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
apipkg                        1.4
apturl                        0.5.2
asn1crypto                    0.24.0
astroid                       1.6.0
asv                           0.5.1
attrs                         21.4.0
Babel                         2.11.0
beautifulsoup4                4.6.0
breathe                       4.7.3
Brlapi                        0.6.6
certifi                       2022.6.15
chardet                       3.0.4
charset-normalizer            2.0.12
click                         6.7
colorama                      0.3.7
command-not-found             0.3
commonmark                    0.9.1
cryptography                  2.1.4
cupshelpers                   1.0
daal                          2021.5.3
daal4py                       2021.5.3
dataclasses                   0.8
decorator                     4.1.2
defer                         1.0.6
distro-info                   0.18ubuntu0.18.04.1
docker                        5.0.3
docutils                      0.18.1
et-xmlfile                    1.1.0
execnet                       1.4.1
html5lib                      0.999999999
httplib2                      0.9.2
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.8.3
importlib-resources           5.4.0
iniconfig                     1.1.1
isort                         4.3.4
Jinja2                        3.0.3
joblib                        1.1.1
keyring                       10.6.0
keyrings.alt                  3.0
language-selector             0.1
launchpadlib                  1.10.6
lazr.restfulclient            0.13.5
lazr.uri                      1.0.3
lazy-object-proxy             1.3.1
logilab-common                1.4.1
louis                         3.5.0
lxml                          4.2.1
macaroonbakery                1.1.3
Mako                          1.0.7
MarkupSafe                    2.0.1
mccabe                        0.6.1
meson                         0.56.2
netifaces                     0.10.4
numpy                         1.19.5
oauth                         1.0.1
olefile                       0.45.1
openpyxl                      3.0.10
packaging                     21.3
pandas                        1.1.5
pexpect                       4.2.1
Pillow                        8.4.0
pip                           21.3.1
pluggy                        1.0.0
prompt-toolkit                1.0.14
protobuf                      3.0.0
psutil                        5.9.1
py                            1.11.0
pycairo                       1.16.2
pycrypto                      2.6.1
pycups                        1.9.73
pyelftools                    0.28
Pygments                      2.13.0
PyGObject                     3.26.1
PyInquirer                    1.0.3
pylint                        1.8.3
pymacaroons                   0.13.0
PyNaCl                        1.1.2
pyparsing                     3.0.9
pyRFC3339                     1.0
pytest                        7.0.1
pytest-forked                 0.2
pytest-xdist                  1.22.1
python-apt                    1.6.5+ubuntu0.7
python-dateutil               2.8.2
python-debian                 0.1.32
pytz                          2018.3
pyxdg                         0.25
PyYAML                        6.0
recommonmark                  0.7.1
regex                         2022.8.17
reportlab                     3.4.0
requests                      2.27.1
requests-unixsocket           0.1.5
roman                         2.0.0
scikit-learn                  0.24.2
scikit-learn-intelex          2021.5.3
scipy                         1.5.4
SecretStorage                 2.3.1
setuptools                    59.6.0
simplejson                    3.13.2
six                           1.11.0
snowballstemmer               2.2.0
Sphinx                        1.8.0
sphinx-rtd-theme              1.1.1
sphinxcontrib-serializinghtml 1.1.5
sphinxcontrib-websupport      1.2.4
ssh-import-id                 5.7
system-service                0.3
systemd-python                234
tbb                           2021.8.0
threadpoolctl                 3.1.0
toml                          0.10.2
tomli                         1.2.3
tomli_w                       0.4.0
torch                         1.10.1
torchvision                   0.11.2
tqdm                          4.64.1
typing_extensions             4.1.1
ubuntu-drivers-common         0.0.0
ufw                           0.36
unattended-upgrades           0.1
urllib3                       1.26.10
usb-creator                   0.3.3
wadllib                       1.3.2
wcwidth                       0.2.5
webencodings                  0.5
websocket-client              1.3.1
wheel                         0.30.0
wrapt                         1.9.0
xkit                          0.0.0
zipp                          3.6.0
zope.interface                4.3.2
~/scikit-learn_bench$

**Comment by lulin789** [comment]
SKL_Bench_Team1 working on this issue

**Comment by napetrov** [comment]
@lulin789  - i think that this particular can be considered a lower priority. 18.04  is pretty old and probably we can consider just setting newer OS requirements  for benchmarks

**Comment by lulin789** [comment]
> @lulin789 - i think that this particular can be considered a lower priority. 18.04 is pretty old and probably we can consider just setting newer OS requirements for benchmarks

ok, then we move to working on this issue:  https://github.com/IntelPython/scikit-learn_bench/issues/102

**Comment by napetrov** [comment]
Will not be implemented -newer versions of Ubuntu should be used for measurements
