### ISSUE TITLE
Unable to run scikit-learn_bench on EMR system

### ISSUE THREAD

**Issue by remahariharan** [IntelPython/scikit-learn_bench#148]
When device=cpu is used, I get the following error. This happens on every benchmark. I have not had any issues running the same on other systems (Intel Xeon Sapphire Rapids based or AMD Zen4 based systems).
**Sample command:** python sklearn_bench/df_clsf.py --arch sys-abcd_os s --data-format pandas --data-order F --dtype float32 --max-features sqrt --device cpu --num-trees 100 --max-depth 8 --file-X-train data/susy_x_train.npy --file-y-train data/susy_y_train.npy --file-X-test data/susy_x_test.npy --file-y-test data/susy_y_test.npy --dataset-name susy

**Traceback (most recent call last):**
  File "/mlperf/scikit-bench/scikit-learn_bench/sklearn_bench/df_clsf.py", line 98, in <module>
    bench.run_with_context(params, main)
  File "/mlperf/scikit-bench/scikit-learn_bench/bench.py", line 564, in run_with_context
    with sycl_context(params.device):
  File "/home/amd/miniconda3/envs/mkl_env/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "src/oneapi/oneapi.pyx", line 118, in sycl_context
  File "src/oneapi/oneapi.pyx", line 46, in daal4py._oneapi.sycl_execution_context.__cinit__
RuntimeError: No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (PI_ERROR_DEVICE_NOT_FOUND)CASE sklearn,df_clsf  --data-format pandas --data-order F --dtype float64 --max-features sqrt --device cpu --num-trees 10 --max-depth 5 JSON DECODING ERROR:
Expecting value: line 1 column 1 (char 0)

**Comment by Alexsandruss** [comment]
Issue is caused by unavailability of CPU device for running with SYCL execution context.
Starting from refactoring (https://github.com/IntelPython/scikit-learn_bench/pull/133), `cpu` device doesn't require to run with this context.
