### ISSUE TITLE
Benchmarks silently execute stock version if scikit-learn-intelex is not installed

### ISSUE THREAD

**Issue by michael-smirnov** [IntelPython/scikit-learn_bench#75]
If I try to run benchmarks with the command like 
```sh
python runner.py --configs configs/skl_xpu_config.json
```
it should run a patched version of scikit-learn algorithms. However, if scikit-learn-intelex package is not installed, benchmarks cannot be patched and should print an error or warning. 

I cannot see the message in https://github.com/IntelPython/scikit-learn_bench/blob/master/bench.py#L204 for some reason.

**Comment by lulin789** [comment]
SKL_Bench_Team1 working on this issue
