### ISSUE TITLE
HistGradientBoostingEstimator

### ISSUE THREAD

**Issue by amueller** [IntelPython/scikit-learn_bench#82]
Hi!
Is there a reason HistGradientBoostingEstimator from sklearn is not included in the benchmark? It should be about as fast as XGBoost.

**Comment by ShvetsKS** [comment]
@amueller thanks a lot for reporting the issue!
We are working on adding the `HistGradientBoostingClassifier`, `HistGradientBoostingRegressor` into current benchmarks.

**Comment by amueller** [comment]
Awesome, thanks!

**Comment by napetrov** [comment]
Will be addressed by https://github.com/IntelPython/scikit-learn_bench/pull/133
